name: Build ZMK Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        shield: [gossiekey_left, gossiekey_right]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install west and dependencies
        run: |
          pip install west
          sudo apt update
          sudo apt install -y ninja-build gperf ccache dfu-util device-tree-compiler wget
          west --version

      - name: Initialize west
        run: west init -l app

      - name: Update west modules
        run: west update

      - name: Export Zephyr CMake package
        run: west zephyr-export

      - name: Build firmware
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG=./config

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.shield }}
          path: build/zephyr/zmk.uf2
