name: Build ZMK Firmware

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shield: [gossiekey_left, gossiekey_right]

    steps:
      - name: Checkout config
        uses: actions/checkout@v3

      - name: Initialize west
        run: west init -l config

      - name: Update west modules
        run: west update

      - name: Export Zephyr CMake package
        run: west zephyr-export

      - name: Build firmware
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG=./config

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.shield }}
          path: build/zephyr/zmk.uf2
