name: ZMK Firmware Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-left:
    name: Build Left Half
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build left firmware
        uses: zmkfirmware/zmk-docker-build@v2
        with:
          board: nice_nano_v2
          shield: gossiekey_left
          config-path: config
          archive-name: gossiekey_left

  build-right:
    name: Build Right Half
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build right firmware
        uses: zmkfirmware/zmk-docker-build@v2
        with:
          board: nice_nano_v2
          shield: gossiekey_right
          config-path: config
          archive-name: gossiekey_right
