name: Build Left and Right Firmware

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shield: [gossiekey_left, gossiekey_right]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install west

      - name: Initialize West
        run: |
          west init -l app
          west update

      - name: Build firmware
        run: |
          west build -s app -b nice_nano_v2 -- -DSHIELD=${{ matrix.shield }}

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.shield }}-firmware
          path: build/zephyr/zmk.uf2
