name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Left and Right Firmware
    runs-on: ubuntu-latest

    strategy:
      matrix:
        shield: [gossiekey_left, gossiekey_right]

    steps:
      - name: Checkout config
        uses: actions/checkout@v3

      - name: Build ZMK firmware
        uses: zmkfirmware/zmk-build-action@v1
        with:
          board: nice_nano_v2
          shield: ${{ matrix.shield }}
          config-path: config
